# Generated by Django 5.0.6 on 2024-09-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeEditor', '0002_bookmodel_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], default='file', max_length=10)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='CodeEditor.filemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='BookModel',
        ),
    ]
