# Generated by Django 5.0.6 on 2024-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeEditor', '0003_filemodel_delete_bookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
