# Generated by Django 5.0.6 on 2024-09-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeEditor', '0004_alter_filemodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
