# Generated by Django 5.0.6 on 2024-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeEditor', '0006_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
