# Generated by Django 5.0.6 on 2024-09-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeEditor', '0007_alter_filemodel_content_alter_filemodel_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
