# Generated by Django 5.0.6 on 2024-09-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevealJsApp', '0002_rename_data_revealjsapp_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevealJsApp',
            new_name='slides',
        ),
    ]
